import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../provider";
import { SidebarItem } from "@repo/ui/sidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "./lib/auth";
import { Wallet, History, QrCode, Settings } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <div className="flex h-screen">
            {/* Sidebar */}
            <div className="w-64 bg-white border-r border-slate-200">
              <div className="flex flex-col h-full">
                {/* Navigation */}
                <div className="flex-1 p-4 space-y-2">
                  <SidebarItem
                    href="/dashboard"
                    title="Dashboard"
                    icon={<Wallet className="w-5 h-5" />}
                  />
                  <SidebarItem
                    href="/transactions"
                    title="Transactions"
                    icon={<History className="w-5 h-5" />}
                  />
                  <SidebarItem
                    href="/qr-code"
                    title="QR Code"
                    icon={<QrCode className="w-5 h-5" />}
                  />
                  <SidebarItem
                    href="/settings"
                    title="Settings"
                    icon={<Settings className="w-5 h-5" />}
                  />
                </div>
              </div>
            </div>

            {/* Main Content */}
            <div className="flex-1 overflow-auto bg-slate-50">
              <main className="p-8">
                {children}
              </main>
            </div>
          </div>
        </body>
      </Providers>
    </html>
  );
}
